[profile.release]
# Allows defmt to display log locations even in release
debug = true

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"